[profile.default]
remappings = [
    "forge-std/=lib/forge-std/src/",
]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
